import { emptyJob, type Job, type Profile } from './types';
const date = (offset: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toLocaleDateString('en-CA', { timeZone: 'Europe/Zurich' });
};
export const demoProfiles: Profile[] = [
  {
    id: 'profile-software',
    version: 0,
    name: 'Software Engineering',
    language: 'en',
    documentId: null,
    text: 'Informatiker EFZ, Applikationsentwicklung. Developed REST APIs in Java and Spring Boot for an internal inventory application. Implemented SQL queries and JPA persistence. Worked in a team using Git pull requests and code reviews. Wrote JUnit tests. German B2, English C1. Familiar with Docker.',
  },
  {
    id: 'profile-support',
    version: 0,
    name: 'IT Support',
    language: 'de',
    documentId: null,
    text: 'Informatiker EFZ. Unterstützung von Mitarbeitenden bei Windows- und Netzwerkproblemen. Dokumentation von Lösungen. Deutsch B2, Englisch C1.',
  },
];
export const demoJobs: Job[] = [
  {
    ...emptyJob(),
    id: 'sample-1',
    version: 0,
    createdAt: date(-9),
    title: 'Junior Software Engineer',
    company: 'Example AG',
    status: 'INTERVIEW',
    location: 'Zürich',
    canton: 'ZH',
    source: 'jobs.ch',
    salaryMin: 75000,
    salaryMax: 82000,
    workload: 100,
    appliedDate: date(-5),
    interviewDate: `${date(5)}T14:00:00+02:00`,
    contactName: 'Anna Müller',
    contactEmail: '',
    profileId: 'profile-software',
    description:
      'Join our application team in Zürich. You will build and maintain Java services using Spring Boot, REST APIs, JPA/Hibernate and SQL. We use Git, JUnit, Docker and Kubernetes. An Informatiker EFZ qualification and German at B2 level are required. AWS experience is preferred.',
    notes:
      'First conversation went well. Prepare an example of a technical problem solved as a team.',
    analysis: {
      summary:
        'A good foundation for this role. Your CV demonstrates the core Java stack. Cloud infrastructure is the clearest gap to discuss honestly.',
      requirements: [
        {
          requirement: 'Java',
          status: 'matched',
          evidence: 'Developed REST APIs in Java and Spring Boot',
          suggestion: '',
        },
        {
          requirement: 'Spring Boot',
          status: 'matched',
          evidence: 'Developed REST APIs in Java and Spring Boot',
          suggestion: '',
        },
        {
          requirement: 'REST APIs',
          status: 'matched',
          evidence: 'Developed REST APIs',
          suggestion: '',
        },
        {
          requirement: 'JPA / Hibernate',
          status: 'partial',
          evidence: 'JPA persistence',
          suggestion:
            'Describe which persistence mappings you implemented; Hibernate is not explicit.',
        },
        {
          requirement: 'SQL',
          status: 'matched',
          evidence: 'Implemented SQL queries',
          suggestion: '',
        },
        {
          requirement: 'Git',
          status: 'matched',
          evidence: 'Git pull requests and code reviews',
          suggestion: '',
        },
        { requirement: 'JUnit', status: 'matched', evidence: 'Wrote JUnit tests', suggestion: '' },
        { requirement: 'German B2', status: 'matched', evidence: 'German B2', suggestion: '' },
        {
          requirement: 'Informatiker EFZ',
          status: 'matched',
          evidence: 'Informatiker EFZ',
          suggestion: '',
        },
        {
          requirement: 'Docker',
          status: 'partial',
          evidence: 'Familiar with Docker',
          suggestion: 'Add a concrete example only if you have one.',
        },
        {
          requirement: 'Kubernetes',
          status: 'missing',
          evidence: '',
          suggestion: 'No evidence in this CV.',
        },
        {
          requirement: 'AWS',
          status: 'missing',
          evidence: '',
          suggestion: 'Preferred experience; be open about the gap.',
        },
      ],
      topics: [],
      questions: [],
      weaknesses: [],
      letter: '',
      changes: [],
    },
  },
  {
    ...emptyJob(),
    id: 'sample-2',
    version: 0,
    createdAt: date(-11),
    title: 'Frontend Developer',
    company: 'Alpine Digital',
    status: 'APPLIED',
    location: 'Bern',
    canton: 'BE',
    salaryMin: 78000,
    salaryMax: 90000,
    workload: 80,
    source: 'LinkedIn',
    appliedDate: date(-8),
    followUpDate: date(0),
    description:
      'Build accessible React and TypeScript applications. Collaborate with design and backend teams. German and English communication skills.',
    profileId: 'profile-software',
  },
  {
    ...emptyJob(),
    id: 'sample-3',
    version: 0,
    createdAt: date(-4),
    title: 'IT Support Specialist',
    company: 'Helvetia Systems',
    status: 'APPLIED',
    location: 'Basel',
    canton: 'BS',
    salaryMin: 65000,
    salaryMax: 74000,
    workload: 100,
    source: 'Indeed',
    appliedDate: date(-3),
    description:
      'Support colleagues with Windows, Microsoft 365 and network troubleshooting. German B2 and a service-oriented mindset.',
    profileId: 'profile-support',
  },
  {
    ...emptyJob(),
    id: 'sample-4',
    version: 0,
    createdAt: date(-2),
    title: 'Java Backend Developer',
    company: 'Limmat Technologies',
    status: 'INTERESTED',
    location: 'Zürich',
    canton: 'ZH',
    salaryMin: 80000,
    salaryMax: 95000,
    workload: 100,
    source: 'Company website',
    description: 'Develop Java and Spring Boot APIs. SQL, testing and Git experience required.',
  },
  {
    ...emptyJob(),
    id: 'sample-5',
    version: 0,
    createdAt: date(-1),
    title: 'Application Developer',
    company: 'Léman Solutions',
    status: 'INTERESTED',
    location: 'Lausanne',
    canton: 'VD',
    salaryMin: 72000,
    salaryMax: 85000,
    workload: 80,
    source: 'jobs.ch',
    description: 'Développement de services web. Java, SQL, français B2 et anglais.',
    language: 'fr',
  },
  {
    ...emptyJob(),
    id: 'sample-6',
    version: 0,
    createdAt: date(-20),
    title: 'Junior Full Stack Developer',
    company: 'Nordlicht Studio',
    status: 'REJECTED',
    location: 'Winterthur',
    canton: 'ZH',
    salaryMin: 70000,
    salaryMax: 78000,
    appliedDate: date(-18),
    source: 'LinkedIn',
    description: 'TypeScript, React and Node.js.',
    notes:
      'They chose a candidate with more professional experience. Keep in touch for future openings.',
  },
];
